### ISSUE TITLE
Fix security bugs by updating dependencies

### ISSUE THREAD

**Issue by santeriv** [santeriv/pulljson#1]

**Comment by devofthings** [comment]
Would like to help you do it :)

**Comment by santeriv** [comment]
I did not notice until now that there are already pull requests waiting to be merged.

![image](https://user-images.githubusercontent.com/170341/94779021-e41a3080-03ce-11eb-97ba-4e317235ead1.png)

**Comment by santeriv** [comment]
Although bot (I) did the work I think you helped me to see that I can solve them myself, thanks.
