### ISSUE TITLE
Check if deploy to heroku button works (3 assignees)

### ISSUE THREAD

**Issue by santeriv** [santeriv/pulljson#13]
* Try heroku button (requires Heroku Hobby/Free account - https://www.heroku.com/pricing)
* Add document CONTRIBUTORS.md 
and add a row to the file
``
nickname - tested heroku button, it worked -> see this https://my-pull-json.herokuapp.com
``
OR
``
nickname - tested heroku button, it did not work: describe what happened
``

**Comment by BRAVO68WEB** [comment]
Assign me

**Comment by rhythm1920** [comment]
Please assign me

**Comment by santeriv** [comment]
Thanks @BRAVO68WEB for fixing it
