### ISSUE TITLE
Improve the docs - add contributors section to readme

### ISSUE THREAD

**Issue by santeriv** [santeriv/pulljson#9]

**Comment by rahullli** [comment]
I would like to work on this issue .

**Comment by kalkisurya** [comment]
@santeriv i would like to work on this issue.

**Comment by sabicd** [comment]
Hey @santeriv! created a PR for [this](https://github.com/santeriv/pulljson/pull/12)!

**Comment by santeriv** [comment]
Thanks merged it.
